### ISSUE TITLE
[Question] Future of this repo

### ISSUE THREAD

**Issue by nicolaasjan** [BPower0036/AdBlockFilters#20]
### Prerequisites / Vereisten

- [ ] This is a **Dutch** website, so no general websites with Dutch subdomains (e.g. nl.y8.com) / 
      Het is een **Nederlandse** website, dus geen websites met Nederlandse subdomeinen (bijv. nl.y8.com)
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue / Geen **duplicaten**!!
    - Your issue may already be reported. / Uw probleem kan al gemeld zijn.
- [ ] I tried to reproduce the issue when...
    - [ ] uBlock Origin with default lists / uBlock Origin met standaard filterlijsten
    - [ ] uBlock Origin is the only extension / uBlock Origin is de enige extensie
- [ ] Only ads or anti-adblock / Alleen advertenties of anti-adblock
    - Privacy staff should be reported at uBlock Origin or EasyPrivacy / Privacy dingen moet u melden aan uBlock of EasyPrivacy
    - No annoyances 

### URL(s) where the issue occurs / Websites waar het probleem voorkomt
N/A

### Describe the issue / Beschrijf het probleem
I saw that your list has been removed from uBO's defaults:
https://github.com/gorhill/uBlock/commit/9e394aa02b9451466fa7f1cca3f7ef9ee2d3d40b
So you might want to remove the following line from [README.md](https://github.com/BPower0036/AdBlockFilters#readme):
`It's now the standard Dutch list in uBlock Origin, see this`

Do you still intend to keep maintaining it?
For now I have added it to my Custom filters.

And is EasyList Dutch being maintained better in the mean time?

 
 

### Screenshot(s)
N/A

### Versions

- Browser/version: Firefox
- uBlock Origin version: 1.35.3b5

**Comment by BPower0036** [comment]
Yes, I still intend to keep maintaining my list.
And EasyList Dutch is NOT better maintained at the mean time.
My list covers still a lot more websites.
 - EasyList Dutch has 429 rules; mine 762.
 - When enabled both, EasyList Dutch uses then 155 rules. (of which most are unnecessary, because they are outdated or unnecessary when using the default uBlock Filters)
 - This al means that my list, EasyDutch, has 488 new rules.

**Comment by BPower0036** [comment]
***UPDATE***
EasyList Dutch is at the moment much better maintained.
However my list has still more rules EasyList Dutch: 913 vs EasyDutch: 1714
Plus the filterrules Khrin form EasyList Dutch makes are not the most preferable rules.
So in my opinion I make far better rules + list is still/better optimized for uBlock Origin and teckles anti-adblock, which EasyList Dutch still isn't and doesn't.

**Comment by BPower0036** [comment]
**Important update**
I moved the EasyDutch filter to an organization https://github.com/EasyDutch-uBO/EasyDutch
It will be maintained over there, so please you the following link in stead of the current one:
https://raw.githubusercontent.com/EasyDutch-uBO/EasyDutch/main/EasyDutch.txt // _**[Subcribe](https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/EasyDutch-uBO/EasyDutch/main/EasyDutch.txt&title=EasyDutch)**_
