### ISSUE TITLE
[NSFW] `sdcash.nl$3p`

### ISSUE THREAD

**Issue by JohnyP36** [BPower0036/AdBlockFilters#23]
### Prerequisites / Vereisten

- [X] This is a **Dutch** website, so no general websites with Dutch subdomains (e.g. nl.y8.com) / 
Het is een **Nederlandse** website, dus geen websites met Nederlandse subdomeinen (bijv. nl.y8.com)

- [X] I performed a [cursory search of the issue tracker](https://github.com/BPower0036/AdBlockFilters/issues) to avoid opening a duplicate issue / 
Geen **duplicaten**!!

- [X] Only ads or anti-adblock / 
Alleen advertenties of anti-adblock

### I tried to reproduce the issue when...

- [X] uBlock Origin with default lists / uBlock Origin met standaard filterlijsten
- [X] uBlock Origin is the only extension / uBlock Origin is de enige extensie

### URL(s) where the issue occurs / Website(s) waar het probleem voorkomt

`www.direct-sexdate.be`
`neuk-sexcontact.be/`

### Describe the issue

By blocking `sdcash.nl$3p` site elements disappear which are **NOT** ads

### uBlock Origin version

1.36.2

### Browser name and version

Edge 92

**Comment by BPower0036** [comment]
It are ads although some don't look like it.
