### ISSUE TITLE
Update Specifieke verbergregels

### ISSUE THREAD

**Issue by JohnyP36** [BPower0036/AdBlockFilters#24]
### Prerequisites / Vereisten

- [X] This is a **Dutch** website, so no general websites with Dutch subdomains (e.g. nl.y8.com) /
Het is een **Nederlandse** website, dus geen websites met Nederlandse subdomeinen (bijv. nl.y8.com)

- [X] I performed a [cursory search of the issue tracker](https://github.com/BPower0036/AdBlockFilters/issues) to avoid opening a duplicate issue /
Geen **duplicaten**!!

- [X] Only ads or anti-adblock /
Alleen advertenties of anti-adblock

### I tried to reproduce the issue when...

- [X] uBlock Origin with default lists / uBlock Origin met standaard filterlijsten
- [X] uBlock Origin is the only extension / uBlock Origin is de enige extensie

### URL(s) where the issue occurs / Website(s) waar het probleem voorkomt

See below in the "describe the issue"

### Describe the issue

See [this list](https://github.com/JohnyP36/Personal-List/commit/85baf6fae4d6700f1b3b852f705329bad524a661) for the rules that don't exist anymore.

### uBlock Origin version

1.36.2

### Browser name and version

Edge 92

**Comment by BPower0036** [comment]
Look better before you open issues.
