### ISSUE TITLE
netonline.be

### ISSUE THREAD

**Issue by JohnyP36** [BPower0036/AdBlockFilters#25]
https://github.com/BPower0036/AdBlockFilters/blob/9073c8f76b33e21a78fa541b17869cad8035f045/EasyDutch/Specifieke_verbergregels.txt#L3

This rule is already blocked by "EasyList / EasyPrivacy" with the rule `##.adsbygoogle`

**Comment by BPower0036** [comment]
No, because I want to delete the element that has `.adsbygoogle` not only `.adsbygoogle`
But this rule cause problems on the homepage so I deleted it.
https://github.com/BPower0036/AdBlockFilters/commit/f9106ad6a2f89e518614278bed53ea53f8268769
