### ISSUE TITLE
Add romagazine.nl 

### ISSUE THREAD

**Issue by JohnyP36** [BPower0036/AdBlockFilters#29]
https://github.com/JohnyP36/Personal-List/commit/c93c72857feb5b39ad18e174212dd26be16ae972

**Comment by JohnyP36** [comment]
You leaved the option to choose a empty template  / `blank issue` I used that one. So that's not invalid.

**Comment by BPower0036** [comment]
@JohnyP36  It is invalid because you have to / **must** follow a issue template. You can only open a blank issue template if there is no suiting issue template for your issue.
