### ISSUE TITLE
How to use "Scriptlet injection" in uBlock Origin

### ISSUE THREAD

**Issue by BPower0036** [BPower0036/AdBlockFilters#3]
If someone sees this issues.

I wanted to learned to add `Scriptlet injection` in/to uBlock.
How do I know what to add?
Where have I to look?

For instance: On `spele.nl` there is an anti-adblock. How can I solve that?

**Comment by okiehsch** [comment]
> How do I know what to add?

That's not easy to answer, it depends. ;)
For a start read https://github.com/gorhill/uBlock/wiki/Resources-Library to look at what each injection does and how it basically works.
In most cases you will have to look at the source to see what function you want to disable.
Your example `spele.nl` is a little bit more complicated.
The site checks if `improvedigital.com/pbw/headerlift.min.js` has been loaded succesfully, if it concludes that it is blocked it will show the ant adblock message.
You can use a [redirection](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#redirect) to "trick" the site into believing that the targeted request has not been blocked.

**Comment by okiehsch** [comment]
Forgot to post the redirection.
`||improvedigital.com/*/headerlift.min.js$script,redirect-rule=noop.js,domain=spele.nl`
works on my end.

**Comment by okiehsch** [comment]
For a rather straightforward example of how to fix an issue using an injection look at
https://github.com/uBlockOrigin/uAssets/issues/8969

If you go to the source of that site `view-source:https://getpaste.link/`
you see
![image](https://user-images.githubusercontent.com/16838044/116350248-e96b1c80-a7f1-11eb-893f-2fee3564d91f.png)

The adblock message is shown if  the property "isAdBlockActive" has the value true
I added the filter `getpaste.link##+js(set, isAdBlockActive, false)` to change the value and the anti adblock issue is fixed.

**Comment by BPower0036** [comment]
@okiehsch Tanks for explaining.
I already looked at https://github.com/gorhill/uBlock/wiki/Resources-Library but didn't how where to look.
Tanks for letting me know you have to look in `view-source:`
