### ISSUE TITLE
Rule on autobahn.eu

### ISSUE THREAD

**Issue by JohnyP36** [BPower0036/AdBlockFilters#34]
### Prerequisites / Vereisten

- [X] This is a **Dutch** website, so no general websites with Dutch subdomains (e.g. nl.y8.com) / Het is een **Nederlandse** website, dus geen websites met Nederlandse subdomeinen (bijv. nl.y8.com)
- [X] I performed a [cursory search of the issue tracker](https://github.com/BPower0036/AdBlockFilters/issues) to avoid opening a duplicate issue / Geen **duplicaten**!!
- [X] Only ads or anti-adblock / Alleen advertenties of anti-adblock

### I tried to reproduce the issue when...

- [X] uBlock Origin with default lists / uBlock Origin met standaard filterlijsten
- [X] uBlock Origin is the only extension / uBlock Origin is de enige extensie

### URL(s) where the issue occurs / Website(s) waar het probleem voorkomt

`autobahn.eu`

### Describe the issue

See https://github.com/BPower0036/AdBlockFilters/commit/1e859d8497f2a8e67a014581331dacf77e1d99ab#r59439166

### uBlock Origin version

1.38.4

### Browser name

Microsoft Edge

### Browser version

95

**Comment by BPower0036** [comment]
See https://github.com/BPower0036/AdBlockFilters/commit/1e859d8497f2a8e67a014581331dacf77e1d99ab#r59459878

**Comment by JohnyP36** [comment]
### But my rule isn't **invalid** 
it just works fine. 

**You definitely don't understand the use of the "invalid" label.**
