### ISSUE TITLE
A: niburu.co elementen

### ISSUE THREAD

**Issue by JohnyP36** [BPower0036/AdBlockFilters#4]
### Prerequisites / Vereisten

- [x] This is a **Dutch** website, so no general websites with Dutch subdomains (e.g. nl.y8.com) / 
      Het is een **Nederlandse** website, dus geen websites met Nederlandse subdomeinen (bijv. nl.y8.com)
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue / Geen **duplicaten**!!
    - Your issue may already be reported. / Uw probleem kan al gemeld zijn.
- [x] I tried to reproduce the issue when...
    - [x] uBlock Origin with default lists
    - [x] or with EasyList and EasyPrivacy
    - [ ] using a new, unmodified browser profile
- [x] Only ads or anti-adblock / Alleen advertenties of anti-adblock
    - Privacy staff should be reported at uBlock Origin or EasyPrivacy / Privacy dingen moet u melden aan uBlock of EasyPrivacy
    - No annoyances 

### URL(s) where the issue occurs / Websites waar het probleem voorkomt
[niburu.co](https://niburu.co/het-complot/16243-ze-hebben-het-gemunt-op-je-pijnappelklier?__cf_chl_jschl_tk__=e002d01072c3fdb425104d156728a71bb6d5887a-1619686544-0-AScphULOInYSouwoO5uM6LjGI7dFlnWJGC1EDrAXlv3CBCDfaV7g8w2Vf_leD9P_SQCIdGLSoO7nTdKSAm2LHvKgmiCcq84QSPeZTCf9Uwf42FPSSEDXARV4k2-YMgWHz4Mr-sOrv2Tq2qzERpblU8YBnfyCska6PkmSW4VfWZyNZGTis2BQjoOgpiXh4a4dyf-brE-KafY3W5LXldaa2vv-hd1_j1I1f0oRDsrI_LTSAAjVApFqu32TWLQvqazzbKul23jnL6z4cVOiFl3oGuXCW2K9UM8h2LPA_c1sR6SepH682mFg2JSGbtpAJC9Z-hhHS6yOPi1xrdbTIigYTMUtjykM9bXxq7seVuUVKnpO_N0R5VPjptreQpP4IwtE8_O2B6OoDzjp_9yp9NhzltoWAJiha278kzKnAxS7fSZTaluEkGA5ggrSrqIiG4DqClntUzwKnBo5yeYSFXy0aFEE3RWC__iUyOqMbrBr5o_dkEM2HCzup2Mar3L1qO8y3TZ9f2TFjeuh7C8CO6nA5MPCKSR4H_eXh_23lXfkM-cv)

### Describe the issue / Beschrijf het probleem

Twee elementen worden niet geblokkeerd: 
 - 1. Sponsors
 - 2. Promotie 
Gebruik de volgende regels: 
 - `niburu.co##.sponsers.moduletable > .border`
 - `niburu.co##div.moduletable:nth-of-type(7) > .border`  

### Screenshot(s)
![image](https://user-images.githubusercontent.com/81161435/116527665-f139c800-a8a8-11eb-97b5-21a2466b85c4.png)
![image](https://user-images.githubusercontent.com/81161435/116527700-fb5bc680-a8a8-11eb-9d03-82175cdb7b36.png)

### Versions

- Browser/version: Edge
- uBlock Origin version: 1.34.0
- AdBlock Plus version: [here]

**Comment by BPower0036** [comment]
Promotions are 1p promotions to other articles on the website. Not going to block that
